/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cateatingpancakes_BasicHand */

#ifndef _Included_com_cateatingpancakes_BasicHand
#define _Included_com_cateatingpancakes_BasicHand
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cateatingpancakes_BasicHand
 * Method:    tilesAway
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_cateatingpancakes_BasicHand_tilesAway
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
