/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cateatingpancakes_hand_CommonSplitter */

#ifndef _Included_com_cateatingpancakes_hand_CommonSplitter
#define _Included_com_cateatingpancakes_hand_CommonSplitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cateatingpancakes_hand_CommonSplitter
 * Method:    __tilesAway
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_cateatingpancakes_hand_CommonSplitter__1_1tilesAway
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
